### ISSUE TITLE
Brunt 

### ISSUE THREAD

**Issue by derek2120** [RobXYZ/homebridge-brunt#10]
hi I'm new to this ive installed the brunt plug in but having trouble installing the config is anyone able to help

**Comment by RobXYZ** [comment]
Sorry, I no longer have any Brunt products so unable to test or maintain this any more.

If you are able to post more details about what you have tried so far and any error messages I may be able to suggest something.

**Comment by derek2120** [comment]
Hi when I’m trying to do the config I copy and
Paste your example config in but put my user and password in and when I save it tells me invalid json
Thanks

On 21 Sep 2023, at 10:03, RobXYZ ***@***.***> wrote:

﻿

Sorry, I no longer have any Brunt products so unable to test or maintain this any more.

If you are able to post more details about what you have tried so far and any error messages I may be able to suggest something.

**Comment by derek2120** [comment]
[image1.jpeg]
Thanks

On 21 Sep 2023, at 12:33, DEREK CLIFFORD ***@***.***> wrote:

﻿ Hi when I’m trying to do the config I copy and
Paste your example config in but put my user and password in and when I save it tells me invalid json
Thanks

On 21 Sep 2023, at 10:03, RobXYZ ***@***.***> wrote:

﻿

Sorry, I no longer have any Brunt products so unable to test or maintain this any more.

If you are able to post more details about what you have tried so far and any error messages I may be able to suggest something.

**Comment by RobXYZ** [comment]
I have made some adjustments that should hopefully fix all the current problems.

Also, the plugin is now configurable via Homebridge UI which should reduce the chance of json errors.

**Comment by derek2120** [comment]
Got it working thanks

On 24 Oct 2023, at 12:17, RobXYZ ***@***.***> wrote:

﻿

I have made some adjustments that should hopefully fix all the current problems.

Also, the plugin is now configurable via Homebridge UI which should reduce the chance of json errors.
