### ISSUE TITLE
Errors after installing plugin and adding brunt to config file

### ISSUE THREAD

**Issue by Silentbob101** [RobXYZ/homebridge-brunt#3]
After installing the brunt plugin and adding brunt settings into the config file I get an error starting homebridge

`
/usr/local/lib/node_modules/homebridge-brunt/lib/bruntapi.js:76
		    if (callback) callback(str);
                    ^
TypeError: Cannot read property 'sessionId' of undefined
    at /usr/local/lib/node_modules/homebridge-brunt/index.js:51:30
    at /usr/local/lib/node_modules/homebridge-brunt/lib/bruntapi.js:137:5
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-brunt/lib/bruntapi.js:76:21)
    at IncomingMessage.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)`

any ideas ?

**Comment by jayl00** [comment]
I am getting exactly the same message as this one. Can anyone help, please?

**Comment by RobXYZ** [comment]
Check the user and pass are correct. User should be your email address.

I will add some better error handling for this in the future!

**Comment by wilsoa45** [comment]
I know this is quite an old three however I'm experiencing the same issue. this is my .json code (with security aspects changed) can you spot anything that wold give me this issue or give any advice to resolve it?

{
    "bridge": {
        "name": "Homebridge B67655454",
        "username": "0E:58:95:45:B6:85",
        "port": 51665,
        "pin": "74-66-96"
    },
    "platforms": [
        {
            "platform": "Brunt",
            "name": "blind",
            "user": "wils.....@email.com",
            "pass": "E......f..s.."
        },
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        }
    ],
    "accessories": [],
    ]
}
